version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      astro:
        patterns:
          - astro
          - "@astrojs/*"
      testing:
        patterns:
          - vitest
          - "@vitest/*"
          - "@playwright/*"
          - "@axe-core/*"
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
